language: csharp
mono: none
dotnet: 3.1.201
script:
  - dotnet restore
  - dotnet test --collect:"XPlat Code Coverage" --settings runsettings.xml
  - dotnet build
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
